### ISSUE TITLE
matching of '.' in path template

### ISSUE THREAD

**Issue by rmallah** [jhthorsen/mojolicious-plugin-openapi#157]
Hi 

looks like its not possible to match the complete data in 
path templates. 

consider below fragment

```
/master/child_places/{geo_id}:
    get:
      tags:
      - masters
      summary: provides list of all countries
      operationId: searchPlaces
      "x-mojo-to": "API#child_places"
      description: |
        This API endpoint searches for countries in platform and returns matching country names.
      produces:
      - application/json

      parameters:
        - name: geo_id
          in: path
          description: the parent place whould child places are to be found.
          required: true
          type: string
         
```

if geo_id has a '.' in it , then only the part before the dot is matched. eg
if /master/child_places/US.MD is requested then 
$c->param('geo_id') will only get 'US' not 'US.MD'
