### ISSUE TITLE
Validation of multipart/form for file upload in V3

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#171]
I have a spec with a standard multipart/form body for a file upload:

```
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  description: something
                  type: string
                  format: binary
              required:
                - files
```

In V2, this was:

```
consumes:
        - multipart/form-data
 parameters:
    - name: files
       in: formData
        required: true
        description: something
        type: file
```

The same client call:

```
$ua->post($url => { form => {files => {file => '/some/file.zip'}});

```

works fine with the V2 spec  but fails in `valid_input` with the V3 spec:

```
[{"message":"Missing property.","path":"\/body\/files"}]

```
I see the file asset in the request on the server:

```
                          parts           => [
                                               bless({
                                                 asset        => bless({
                                                                   auto_upgrade => 1,
                                                                   content => "PK\3........
```

Is this an issue withe validation in the plugin or am I missing something here?
