### ISSUE TITLE
Root path in generated json spec is incorrect

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#174]
In think, since 3.30, I see this issue. Using Swagger UI to load a YAML spec:

```
https://swaggerui/?url=https://prod:3000/v1.json
```

with this in the spec:

``
servers:
  - url: 'https://prod:3000/v1'
    description: PROD server
  - url: 'https://dev:3000/v1'
    description: NONPROD server
```

results in a spec being generated by the plugin and loaded by Swagger UI that looks like this:

``
servers:
  - url: 'https://prod:3000/v1.json'
    description: PROD server
  - url: 'https://dev:3000/v1'
    description: NONPROD server
```

This breaks all "Try it Out" curl URLs due to the added ".json" - seems to be using the URL used to call the API as root instead of the spec root?
