### ISSUE TITLE
Default boolean values for yaml are turned into empty strings

### ISSUE THREAD

**Issue by ugexe** [jhthorsen/mojolicious-plugin-openapi#24]
```
definitions:
  data:
    type: object
    properties:
      bool_value:
        type: boolean
        default: false
```
is turned into:
```
"definitions" : {
  "data" : {
    "type" :"object",
    "properties" : {
      "bool_value" : {
        "default" : "",
        "type" : "boolean"
      }
    }
  }
}
```
Not sure if this is a limitation of yml or a bug with coercion.
