### ISSUE TITLE
Posting an Array of Objects as a body parameter not supported in OpenAPI v2

### ISSUE THREAD

**Issue by lafokamotion** [jhthorsen/mojolicious-plugin-openapi#240]
Similar issue to https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/219

Except the body parameter is an array of objects containing a string as shown:
```
parameters:
  - name: echo
    in: body
    description: Text that should be echoed
    schema:
      type: array
      minItems: 1
      items:
        type: object
        required:
          - record
        properties:
          record:
            type: string
```

The idea being that we have a service that can take one or more items in a POST, shouldn't the spec be able to accept a json object such as:
```
[ { record => 'foo' }, { record => 'bar' } ]
```

However, when calling `$c->openapi->valid_input()`, the following message is received:
```
{
      errors => [
                  {
                    message => "Expected object - got string.",
                    path => "/echo/0",
                  },
                ],
      status => 400,
    }
```

This also is not an issue for OpenAPI v3 as I've tested the behavior there too.

Perl module versions:

- **Mojolicious**: 9.30
- **Mojolicious::Plugin::OpenAPI**: 5.07
- **JSON::Validator**: 5.12
