### ISSUE TITLE
CRITICAL BUG! Something (the validator?!)  drops routes with the same path and different HTTP method

### ISSUE THREAD

**Issue by XSven** [jhthorsen/mojolicious-plugin-openapi#258]
This is an an extract of my OpenAPI spec
```yaml
...
paths:
  /databases/{databaseId}:
    post:
      operationId: create_database
      x-mojo-to:
        controller: Controller::Databases
        action: create
  /databases/{databaseId}:
    get:
      operationId: read_database
      x-mojo-to:
        controller: Controller::Databases
        action: read
  /databases/{databaseId}/tables/{tableId}:
    get:
      operationId: read_table
      x-mojo-to:
        controller: Controller::Tables
        action: read
```
The path `/databases/{databaseId}` is used for **post** (`Controller::Databases#create`) and **get** (`Controller::Databases#read`). Unfortunately the **post** route is dropped

```
  DB<52> x $self->validator->routes
0  Mojo::Collection=ARRAY(0x1146960a0)
   0  HASH(0x1145daad0)
      'method' => 'get'
      'operation_id' => 'read_table'
      'path' => '/databases/{databaseId}/tables/{tableId}'
   1  HASH(0x114696208)
      'method' => 'get'
      'operation_id' => 'read_database'
      'path' => '/databases/{databaseId}'
```

```
perl  script/my_app routes
/rest/fas-database-manager/v1                  *        restfasdatabasemanagerv1
  +/                                           GET
  +/databases/<:databaseId>/tables/<:tableId>  GET      "read_table"
  +/databases/<:databaseId>                    GET      "read_database"

```

**Comment by XSven** [comment]
If OpenAPI only allows one HTTP method per path, could an exception be raised instead of dropping one route randomly?

**Comment by HEM42** [comment]
Hi

It looks like your spec is defined incorrectly, when you have multiple methods, it should be defined under the same endpoint

```
...
paths:
  /databases/{databaseId}:
    post:
      operationId: create_database
      x-mojo-to:
        controller: Controller::Databases
        action: create
    get:
      operationId: read_database
      x-mojo-to:
        controller: Controller::Databases
        action: read
  /databases/{databaseId}/tables/{tableId}:
    get:
      operationId: read_table
      x-mojo-to:
        controller: Controller::Tables
        action: read
```
