### ISSUE TITLE
security definitions

### ISSUE THREAD

**Issue by chandwki** [jhthorsen/mojolicious-plugin-openapi#36]
It looks like the plugin completely ignores security definitions. It would be really nice to be able to have an authentication method route to an auth controller and method.

For example,

```
securityDefinitions:
  AccessToken:
    x-mojo-to: 'user#token_auth'
    description: |
      For accessing the API a valid JWT token must be passed in the 'Authorization' header. A valid JWT token is generated by the /auth endpoint.

      The following syntax must be used in the 'Authorization' header:
        Bearer: xxxxxx.yyyyyyy.zzzzzz
    type: apiKey
    name: Authorization
    in: header
```
I know you can specify a single custom route to do authentication but the problem is that this is a catch all and doesn't support multiple authentication methods.

The problem I was running into is if I have a `/api/login` route that generates a JWT token obviously I don't want it to authenticate a JWT token that doesn't exist yet!
