### ISSUE TITLE
Array items in querystring

### ISSUE THREAD

**Issue by kak-tus** [jhthorsen/mojolicious-plugin-openapi#37]
If I am using parameters in querystring - validation fails, if only one parameter specified.

curl '...?phone=1&phone=2' - success
curl '...?phone=1' - fail with error: Expected array - got string.","path":"\/phone

Schema example
```
    get:
...
      parameters:
        -
          in: query
          name: phone
          type: array
          required: true
          minItems: 1
          items:
            type: string
```
