### ISSUE TITLE
Headers validation

### ISSUE THREAD

**Issue by elcamlost** [jhthorsen/mojolicious-plugin-openapi#5]
Mojolicious application (if it stays behind some frontend server like nginx) get headers in uppercase and converts standard headers to its original names in Mojo::Headers package.

So if i desclare header parameter like this:
```
parameters:
  some-header-param:
    name: CamelCase
    required: true
    type: string
```
and client sends this header, JSON::Validator::OpenApi will get header name as CAMELCASE (via mojo_ctrl->req->headers->to_hash) and validation will fail.

What is recommended way to deal with this situation?
