### ISSUE TITLE
defaults broken in 1.22?

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#53]
I just upgraded to 1.22 and immediately defaults for enums are not being passed as params any more. I have this in the spec:

```
  PCVersion:
    name: pcversion
    type: string
    in: query
    description: version of commands which will run on backend
    default: 10.1.0
    enum:
      - 9.6.1
      - 10.1.0
```

before, params always had "10.1.0" as the value of "pcversion" if nothing was passed but now it's just empty ...
