### ISSUE TITLE
`operationId` broke route

### ISSUE THREAD

**Issue by KES777** [jhthorsen/mojolicious-plugin-openapi#74]
For case when routes are defined in application as next:

/countries | * | "countries"
-- | -- | --
+/:id | GET | "show_country"
+/:id | PUT | "update_country"

Where countries route define `controller#` and show/update country define `#action`

Then `spec`:
```
paths:
  /countries/{id}:
    get:
      operationId: show_country
```

will cause `show_country` moved under `/api`. And it will be broken because it have not info about controller
